Anand Kulkarni - 26/01/2020 11:05:11:105 Asia/Singapore(+08,+0800) - scripts renamed. Aiming to package this tool as rpm for ease of usage across different installations.

diff --git a/fcpkgmon b/fcpkgmon
--- a/fcpkgmon
+++ b/fcpkgmon
@@ -4,8 +4,13 @@
 # Date : 01/01/2020 : Started building the package mon utility to pull packages and deploy them as much as possible without any end user interaction and ease of use.
 # Identify if there is root user who is running this.
 
-# Import library functions here.
-. ${PWD}/pkgMonLib
+# Import library functions here.Identify if it exists.If not simply exit with error.
+if [ ! -f /usr/local/lib/fcpkgmonlib.sh ]; then
+	echo -e "Fatal Error : The library fcpkgmonlib.sh was not found at /usr/local/lib path.Exiting with failure..."
+	exit 1
+else
+	. /usr/local/lib/fcpkgmonlib.sh
+fi 
 
 # validate running user.
 isRoot=$(isUserRoot)
